X = int(input("podaj współrzędną x: "))
Y = int(input("podaj współrzędną y: "))
if X>0 and Y>0: print(f"Point P({X},{Y}) is in the first quadrant")
elif X>0 and Y<0: print(f"Point P({X},{Y}) is in the second quadrant")
elif X<0 and Y<0: print(f"Point P({X},{Y}) is in the third quadrant")
elif X<0 and Y>0: print(f"Point P({X},{Y}) is in the fourth quadrant")
elif X==0 and Y==0: print(f"Point P({X},{Y}) is in the (0,0) position")
elif X==0 and Y!=0: print(f"Point P({X},{Y}) is on the Y axis")
elif X!=0 and Y==0: print(f"Point P({X},{Y}) is on the X axis")